"use client";

import { useEffect } from "react";

/**
 * Registers the service worker (PWA) in production builds.
 *
 * Registration is skipped in development because the service worker is
 * only generated by `next build` (see `next.config.ts`). Failures are
 * non-fatal: the app keeps working without offline support.
 */
export function RegisterServiceWorker() {
  useEffect(() => {
    if (process.env.NODE_ENV !== "production") {
      return;
    }
    if (!("serviceWorker" in navigator)) {
      return;
    }

    const onLoad = () => {
      navigator.serviceWorker.register("/sw.js").catch(() => {
        // Unsupported environments (e.g. non-HTTPS previews) can fail
        // here; this must not break the application.
      });
    };

    window.addEventListener("load", onLoad);
    return () => window.removeEventListener("load", onLoad);
  }, []);

  return null;
}
