#!/usr/bin/env node
/**
 * Prints a stable hash of the schema contract so the backend repo can pin it:
 *
 *   -- contract: sha256/1a2b3c…   (first line of each migration file)
 *
 * Only the files that actually change the shape of the API are hashed
 * (SQL + the shared types), so editing prose docs never invalidates it.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const files = [
  "contracts/types/database.types.ts",
  ...readdirSync(join(root, "contracts/sql"))
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((f) => `contracts/sql/${f}`),
].filter((f) => {
  try {
    readFileSync(join(root, f));
    return true;
  } catch {
    return false;
  }
});

const hash = createHash("sha256");
for (const f of files) {
  hash.update(f);
  hash.update("\0");
  hash.update(readFileSync(join(root, f)));
  hash.update("\0");
}

const digest = `sha256/${hash.digest("hex")}`;
const body = [
  digest,
  "",
  "# Generated by `npm run contract:hash`. Pin this value in the header of your first",
  "# migration in cepzk_atendimentos_backend so a later edit to the contract is detectable:",
  "#",
  "#   -- contract: sha256/…",
  "#",
  "# The hash file is intentionally NOT part of its own input (a file cannot contain",
  "# its own digest), and prose docs are excluded so rewording never invalidates it.",
  "",
  ...files.map((f) => `  ${f}`),
  "",
].join("\n");

if (process.argv.includes("--write")) {
  writeFileSync(join(root, "contracts/CONTRACT.sha256"), body);
  console.log("wrote contracts/CONTRACT.sha256");
}
console.log(digest);
